---
- name: Install htop and iotop
  package:
    name: htop,iotop
- name: Install nmon
  package:
    name: nmon
  when: ansible_os_family != 'RedHat' or ansible_distribution_major_version != '7'
- block:
    - copy: src=check_systemd_status.sh dest=/usr/local/bin/check_systemd_status mode=755
    - template: src=systemd-check-cron.j2 dest=/etc/cron.d/systemd-check-cron mode=644
  when: no_networking is undefined and no_snitches is undefined
